-- MySQL Script generated by MySQL Workbench
-- Mon Aug 24 14:58:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oytlab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oytlab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oytlab` DEFAULT CHARACTER SET utf8 ;
USE `oytlab` ;

-- -----------------------------------------------------
-- Table `oytlab`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`doctor` (
  `iddoctor` INT NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddoctor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oytlab`.`pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`pacientes` (
  `idpacientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `edad` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idpacientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oytlab`.`fecha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`fecha` (
  `idfecha` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  PRIMARY KEY (`idfecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oytlab`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oytlab`.`subcategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`subcategoria` (
  `idsubcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idsubcategoria`),
  INDEX `fk_subcategoria_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_subcategoria_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `oytlab`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oytlab`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`solicitud` (
  `idsolicitud` INT NOT NULL AUTO_INCREMENT,
  `doctor_iddoctor` INT NOT NULL,
  `pacientes_idpacientes` INT NOT NULL,
  `fecha_idfecha` INT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idsolicitud`),
  INDEX `fk_solicitud_doctor_idx` (`doctor_iddoctor` ASC) VISIBLE,
  INDEX `fk_solicitud_pacientes1_idx` (`pacientes_idpacientes` ASC) VISIBLE,
  INDEX `fk_solicitud_fecha1_idx` (`fecha_idfecha` ASC) VISIBLE,
  INDEX `fk_solicitud_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_solicitud_doctor`
    FOREIGN KEY (`doctor_iddoctor`)
    REFERENCES `oytlab`.`doctor` (`iddoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_pacientes1`
    FOREIGN KEY (`pacientes_idpacientes`)
    REFERENCES `oytlab`.`pacientes` (`idpacientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_fecha1`
    FOREIGN KEY (`fecha_idfecha`)
    REFERENCES `oytlab`.`fecha` (`idfecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `oytlab`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
