-- MySQL Script generated by MySQL Workbench
-- Tue Sep  8 12:04:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oytlab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oytlab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oytlab` DEFAULT CHARACTER SET utf8 ;
USE `oytlab` ;

-- -----------------------------------------------------
-- Table `oytlab`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreCategoria` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oytlab`.`subCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`subCategoria` (
  `idsubCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombreSubCategoria` VARCHAR(45) NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idsubCategoria`),
  INDEX `fk_subCategoria_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_subCategoria_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `oytlab`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oytlab`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`paciente` (
  `idpaciente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `cedula` INT NULL,
  `fechaExamen` DATE NULL,
  `lugar` VARCHAR(45) NULL,
  PRIMARY KEY (`idpaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oytlab`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `paciente_idpaciente` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_paciente1_idx` (`paciente_idpaciente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_paciente1`
    FOREIGN KEY (`paciente_idpaciente`)
    REFERENCES `oytlab`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oytlab`.`pedido_has_subCategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`pedido_has_subCategoria` (
  `pedido_idpedido` INT NOT NULL,
  `subCategoria_idsubCategoria` INT NOT NULL,
  PRIMARY KEY (`pedido_idpedido`, `subCategoria_idsubCategoria`),
  INDEX `fk_pedido_has_subCategoria_subCategoria1_idx` (`subCategoria_idsubCategoria` ASC) VISIBLE,
  INDEX `fk_pedido_has_subCategoria_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_subCategoria_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `oytlab`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_subCategoria_subCategoria1`
    FOREIGN KEY (`subCategoria_idsubCategoria`)
    REFERENCES `oytlab`.`subCategoria` (`idsubCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oytlab`.`pedido_has_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oytlab`.`pedido_has_categoria` (
  `pedido_idpedido` INT NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`pedido_idpedido`, `categoria_idcategoria`),
  INDEX `fk_pedido_has_categoria_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  INDEX `fk_pedido_has_categoria_pedido1_idx` (`pedido_idpedido` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_has_categoria_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `oytlab`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_categoria_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `oytlab`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
